# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'salt-apps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for salt-apps
  
  pod 'Sample3', :git => "https://github.com/sandipermata/sample3.git"

end
